name: D9 Brewing Company
favicon: null
layout_spectrum: 0.20107057131826878
typography_spectrum: 0.19553398643620312
title: D9 Brewing Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9049167830962688
  lightness: 0.4242685604840517
  saturation: 0.6707094295416027
  rhythmicContrast: 0.8207387300208211
purpose: []
